on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  main-job:
    steps:
      name: first-step
      run: |
        if [[ ${{ "secrets.SUPER_SECRET" -eq 15 }}]]; then
          echo 'SUCCESS'
        else
          echo 'FAIL'
          exit 1
        fi
